### ISSUE TITLE
Perl files use fixed Perl path

### ISSUE THREAD

**Issue by ikirker** [cancerit/grass#12]
We've been installing grass on our cluster for some users as part of the cancerit set, and it seems that the Perl scripts in this repo use:

```bash
#!/usr/bin/perl
```

We don't keep copies of Perl intended for user applications at that path, and I know e.g. MacPorts and PerlBrew can result in installations of Perl being in other different locations.

The usual way of portably writing this is:

```bash
#!/usr/bin/env perl
```

which uses the user's `$PATH` to determine where to find Perl. We currently use `sed` to alter the scripts in our installation, but in general it would probably be useful for other users as well to do this.

I know it's a pretty minor tweak in the code; if you'd like it as a PR I can do that but sometimes people prefer not to complicate the contributor logs.

(Or, if there's a specific reason for doing it this way, that's fine too, but I don't see one in this case.)

(Sorry for the bother.)

**Comment by keiranmraine** [comment]
If you install the perl code (via make).  `#!/usr/bin/perl` is rewritten to the path of the perl found in the environment at that time.  This makes the code execute as expected.

If you choose to not install through make you will always have to prefix the script with `perl `.

We don't use `#!/usr/bin/env perl` as that isn't rewritten by perls `ExtUtils::MakeMaker'.

We expect the code to be installed via `setup.sh` so that all anticipated dependancies are installed too.

**Comment by keiranmraine** [comment]
Wrong button

**Comment by ikirker** [comment]
@keiranmraine Ah, I see. Thanks, and sorry for the bother: I'm not that familiar with Perl build tooling. I'll see about reviewing our scripting and make sure we're using the correct mechanisms.
